name: Send watchlist CSV by email

on:
  schedule:
    - cron: "58 7 * * 1-5"   # 08:58 CET (téli)
    - cron: "58 6 * * 1-5"   # 08:58 CEST (nyári)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) TELJES CSV csatolmányként (backup)
      - name: Send WATCHLIST CSV DAILY (attachment only)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          secure: true
          subject: "WATCHLIST CSV DAILY"
          body: "Daily watchlist attached as CSV (UTF-8, LF)."
          attachments: |
            docs/watchlist.csv

      # 2) MINIMÁL lista (Ticker,Darabszám) – LEVÉL TÖRZSÉBEN
      - name: Build MIN (Ticker,Darabszám)
        id: build_min
        shell: bash
        run: |
          # írunk egy kis Python scriptet fájlba (nincs here-doc redirect a python során)
          cat > build_min.py <<'PY'
          import csv, io, pathlib
          p = pathlib.Path("docs/watchlist.csv")
          data = p.read_text(encoding="utf-8", errors="replace")

          # próbáljuk "," majd ";" elválasztóval
          rows = []
          for delim in (",", ";"):
              rdr = csv.reader(io.StringIO(data), delimiter=delim)
              rows = list(rdr)
              if rows and len(rows[0]) >= 2:
                  break

          out = ["Ticker,Darabszám"]
          for r in rows[1:]:
              t = (r[0] if len(r) > 0 else "").strip()
              d = (r[1] if len(r) > 1 else "").strip()
              if t:
                  out.append(f"{t},{d}")

          pathlib.Path("min_watchlist.txt").write_text("\n".join(out) + "\n", encoding="utf-8")
          PY

          # futtatjuk a scriptet
          python build_min.py

          # a min_watchlist.txt tartalmát kitéve a step outputjába
          {
            echo 'body<<EOF'
            cat min_watchlist.txt
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Send WATCHLIST MIN (inline)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          secure: true
          subject: "WATCHLIST MIN"
          body: ${{ steps.build_min.outputs.body }}
