name: Send watchlist CSV by email

on:
  schedule:
    - cron: "58 7 * * 1-5"
    - cron: "58 6 * * 1-5"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build email body from CSV
        id: csv
        run: |
          {
            echo 'body<<EOF'
            echo "WATCHLIST CSV $(date -u +'%Y-%m-%d') (UTC)"
            echo
            echo '-----BEGIN CSV-----'
            cat docs/watchlist.csv
            echo '-----END CSV-----'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Send email with CSV (inline + attachment)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          secure: true
          subject: "WATCHLIST CSV ${{ github.run_id }}"
          html_body: |
            <p>Daily watchlist CSV inline:</p>
            <pre>${{ steps.csv.outputs.body }}</pre>
          attachments: |
            docs/watchlist.csv
